### ISSUE TITLE
Aligner error?

### ISSUE THREAD

**Issue by miguelballesteros** [jflanigan/jamr#19]
Hi thanks for this tool,

I got this error while running the aligner:

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
	at edu.cmu.lti.nlp.amr.CorpusTool$$anonfun$main$1.apply(CorpusTool.scala:48)
	at edu.cmu.lti.nlp.amr.CorpusTool$$anonfun$main$1.apply(CorpusTool.scala:43)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at edu.cmu.lti.nlp.amr.CorpusTool$.main(CorpusTool.scala:43)
	at edu.cmu.lti.nlp.amr.CorpusTool.main(CorpusTool.scala)

(I removed the last line of ALIGN.sh to keep the /tmp files) and by looking at the /tmr/*.tok file it seems that the last amr graph is not printed (while its ::snt, ::id are printed). 
I tried removing the last sentence and running it again, it didn't help. Same behavior.
I tried hacking it doing the tokenization by myself; it didn't help.

I managed to run it in the first sentence of the same dataset without problems.
I managed to run it with other AMR datasets.

any ideas?

thank you,
Miguel

**Comment by miguelballesteros** [comment]
My bad, I had an error in one sentence: Instead of ::snt I had ::s:nt (not sure why)
